name: Build M2Ds

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Server
        run: cd Tools && .\MS2Create.exe ../Server ../ Server MS2F
      - name: Build XML
        run: cd Tools && .\MS2Create.exe ../Xml ../ Xml MS2F
      - name: Hash Server
        run: certutil -hashfile Server.m2d MD5 > Server.m2d.txt
      - name: Hash Xml
        run: certutil -hashfile Xml.m2d MD5 > Xml.m2d.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            Server.m2d
            Server.m2h
            Xml.m2d
            Xml.m2h
            Server.m2d.txt
            Xml.m2d.txt

